# Generated by Django 3.2.2 on 2021-05-09 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlinecontroller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_type', models.CharField(max_length=64)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.CharField(max_length=5)),
                ('destination_airport', models.CharField(max_length=5)),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airlinecontroller.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email_address', models.CharField(max_length=64)),
                ('phone_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('gate_number', models.IntegerField(default=0)),
                ('refund_status', models.CharField(max_length=64)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airlinecontroller.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airlinecontroller.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airlinecontroller.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='FlightCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.CharField(max_length=64)),
                ('co_pilot', models.CharField(max_length=64)),
                ('flight_engineer', models.CharField(max_length=64)),
                ('navigator', models.CharField(max_length=64)),
                ('flight_scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airlinecontroller.flightcrew'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL),
        ),
    ]
