# Generated by Django 3.2.2 on 2021-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlinecontroller', '0002_auto_20210509_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcrew',
            name='crew_name',
            field=models.CharField(default='NONAME', max_length=64),
        ),
    ]
