# Generated by Django 3.2.2 on 2021-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlinecontroller', '0004_auto_20210515_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateTimeField(verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateTimeField(verbose_name='Departure Date'),
        ),
    ]
