# Generated by Django 3.2.2 on 2021-06-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlinecontroller', '0005_auto_20210515_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
