# Generated by Django 3.2.2 on 2021-06-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlinecontroller', '0007_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
