# Generated by Django 3.2.2 on 2021-06-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlinecontroller', '0008_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=64)),
                ('price', models.IntegerField(default=0)),
                ('gate_number', models.IntegerField(default=0)),
                ('refund_status', models.CharField(max_length=64)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airlinecontroller.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airlinecontroller.passenger')),
            ],
        ),
    ]
