# Generated by Django 3.2.2 on 2021-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlinecontroller', '0009_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='gate_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='flight',
            name='gate_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
