# Generated by Django 3.2.3 on 2021-06-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlinecontroller', '0010_auto_20210604_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_airport',
            field=models.CharField(max_length=30),
        ),
    ]
